feat: add project entities
aplatkouski/travel-app pull request #2
Opened 2021-03-06 07:22 UTC by natallia-js

Добавлены интерфейсы сущностей для работы и общения с сервером.
Для обсуждения.

ICountry - используем на главной странице (id отдает сервер, он нужен для запроса детальной информации по стране)

ICountryDetailed - используем на странице страны (массив элементов ISight - массив достопримечательностей)

ISight - достопримечательность (id нужен, чтобы сообщать серверу о проставлении рейтинга пользователем; массив объектов { userId: string; rating: number } - для хранения рейтинга с привязкой к конкретным пользователям, здесь только id пользователя, остальную информацию можно будет запросить при необходимости и получить в IUser, но можно и сразу получить здесь, тогда вместо { userId: string; rating: number } можно сделать { userName: string; rating: number } и при желании прикрутить еще фотку пользователя: { userName: string; rating: number; userPhotoPath: string })

IUser - здесь есть необязательные поля: id и token не нужны в IUserRegisterData, т.е. при регистрации пользователя; при запросе информации по рейтингам не нужен token и, возможно, фото и id; для вошедшего в систему пользователя используются все поля

IUserRegisterData - данные, вводимые пользователем при регистрации, будем использовать login, password, name, photo, причем фото не обязательно

2021-03-06 14:17 UTC, aplatkouski requested changes
Прошу посмотреть мои замечания и отписать своё мнение, если есть возражения. В противном случае, изменить интерфейсы

2021-03-06 14:17 UTC, aplatkouski commented on src/entities/countryDetailed.ts
> +import ICountry from './country';
В названиях файлов лучше не использовать ``camelCase``, файл переимеовать в ``country-detailed``

Обусловленно это тем, как по разному операционные системы Windows и Linux обрабатывают файлы в названии которых есть заглавные буквы.

2021-03-06 14:17 UTC, aplatkouski commented on src/entities/country.ts
> +  photoPath: string;
``Path`` необходимо заменить на ``Url``, т.к. ``path`` больше применим к данным доступным локально на компьютере, а url к веб-адресу.

2021-03-06 14:17 UTC, aplatkouski commented on src/entities/countryDetailed.ts
> +  shortDescription: string;
У нас нет ``fullDescriptioin``, поэтому можно убрать лишний в данном случае префикс ``short``

2021-03-06 14:17 UTC, aplatkouski commented on src/entities/countryDetailed.ts
> +  [index: number]: ISight;
В стране будет более одной достопримечательности, т.е. здесь нужно использовать массив:
`[index: number]: ISight` стоит заменить на `sights: Array<ISight>`

2021-03-06 14:17 UTC, aplatkouski commented on src/entities/sight.ts
> +  shortDescription: string;
`short` можно удалить

2021-03-06 14:17 UTC, aplatkouski commented on src/entities/sight.ts
> +  photoPath: string;
`Path` -> `Url`

2021-03-06 14:17 UTC, aplatkouski commented on src/entities/sight.ts
> +  [index: number]: { userId: string; rating: number };
Каждой достопримечательности оценку может выставить более чем один пользователь, и здесь нужно ипользовать массив
`[index: number]: ...` -> `reviews: Array<IReview>` предварительно объявив `IReview` или `reviews: Array<{userId: string; rating: number}>`, чтобы не усложнять.

2021-03-06 14:17 UTC, aplatkouski commented on src/entities/userRegisterData.ts
> +import IUser from './user';
Переименовать файл `userRegisterData` в `user-registration-data`

2021-03-06 14:17 UTC, aplatkouski commented on src/entities/userRegisterData.ts
> +interface IUserRegisterData extends IUser {
Думаю стоит немного изменить структура `IUser` и `IUserRegistrationData`

У нас есть следующие события, определяющие интерфейсы:
 - Авторизация пользователя
 - Регистрация пользователя
 - Нахождение пользователя в системе после авторизации

Авторизация: нужен логи и пароль
```ts
interface IUserAuthorizationData {
  login: string;
  password: string;
}
```

Регистрация:
```ts
interfae IUserRegistrationData extends IUserAuthorizationData {
  name: string;
  photo: any;
}
```
Данные пользователя, полученыне от сервера и нужные для корректного выставления оценок и подтверждения самого факта, что авторизация была выполнена успешно
```ts
interface IUser extends IUserAutho {
   token: string; // он является обязательным, иначе не понятно как проверить, что пользователь залогинен
   id: string; // необходим, чтобы убедиться, что пользователь уже проголосовал над достопримечательностью
               // у нас там используется userID, и не дать ему это сделать второй раз. Хотя можно переложить 
               // проверку на серверную часть, и тогда ID не нужен
   login: string // опционально, чтобы было что отображать в header 
   photoUrl: string; // чтобы было что отображать в header после залогивания (чтобы подвердить, что мы 
                     // умеем обрабатывать сохранение в БД фото пользователя
}
```
Прим этом, даже если решим оставить `login` можно описать интерфейс, как
```ts
interface IUser extends Omit<IUserAuthorizationData, "password"> {
 // здесь удаляем login
 }

но, проще просто его исключить

И замечание по поводу `photo: any` - это место, где у нас возникает первый вопрос.

Т.к. ты предложила не хранить в БД бинарные файлы, нет ни какой проблемы с "предустановленными" данные (фото стран и т.д.), но, что делать с данными, которые нам не известны заранее. Ведь мы их не можем залить заранее на  файлообменник. Думаю, нужно найти способ загрузить фото в БД, возможно наложив ограничения на размер файла, далее конвертировать в тот же base64 и хранить в БД, как текст, тогда на стороне клиента возвращать base64 -> bin и корректно отображать изображение

2021-03-06 14:17 UTC, aplatkouski commented on src/entities/country.ts
> +  id: string;
Т.к. `id: string` является "сквозным" в нескольких интерфейсах, лучше вынести его в отдельный файл `id.ts` и описать его через алиас типа:
```ts
type ID = string;

export default ID;
```

2021-03-06 14:42 UTC, aplatkouski commented
@natallia-js тебе нужно выполнить:
```sh
git rebase travel-app feature/project-entities
```
Т.е. сейчас твой коммит находится "позади" текущий версии travel-app

2021-03-06 16:48 UTC, natallia-js commented on src/entities/userRegisterData.ts
> +interface IUserRegisterData extends IUser {
IUserAuthorizationData - OK
IUserRegistrationData extends IUserAuthorizationData - OK
IUser extends IUserAuthorizationData - не OK: зачем нам логин и пароль вошедшего в конкретно данную систему пользователя? Его можно поприветствовать просто по имени.

Т.е. я бы сделала так:
`interface IUser extends Omit<IUserRegistrationData, "login"|"password"> {`
`token: string; /* здесь сервер "зашить" может любую информацию, в т.ч. id `
`пользователя, но эта информация может быть доступна только `
`самому серверу; таким образом, можно не иметь id пользователя на `
`клиенте и все, что связано с рейтингами, делать посредством запросов на сервер*/`
`photoUrl: string;`
`}`

По `photo: any`:  предлагаю заменить на `photoUrl: string`.
Абсолютно нормальная практика хранения больших данных (фото, видео...) в файловой системе на сервере, а в БД - лишь ссылка на соответствующий ресурс.
Не нужно пытаться запихнуть в БД то, что туда не влазит.
К тому же, web-сервер и ОС могут кешировать эти данные... чего не скажешь о запросах к БД.

2021-03-06 17:54 UTC, aplatkouski commented on src/entities/userRegisterData.ts
> +interface IUserRegisterData extends IUser {
@natallia-js вы писали:

## 1. 
> IUser extends IUserAuthorizationData - не OK: зачем нам логин и пароль вошедшего в конкретно данную систему пользователя? Его можно поприветствовать просто по имени.
> 

**Абсолютно согласен**, участок кода `interface IUser extends IUserAutho {`, в моём примере был ошибкой copy-paste, там должно было быть написано: `interface IUser {` - исправил

## 2.

> Т.е. я бы сделала так:
> `interface IUser extends Omit<IUserRegistrationData, "login"|"password"> {`
> `token: string; /* здесь сервер "зашить" может любую информацию, в т.ч. id `
> `пользователя, но эта информация может быть доступна только `
> `самому серверу; таким образом, можно не иметь id пользователя на `
> `клиенте и все, что связано с рейтингами, делать посредством запросов на сервер*/`
> `photoUrl: string;`
> `}`
> 
> По `photo: any`: предлагаю заменить на `photoUrl: string`.
> Абсолютно нормальная практика хранения больших данных (фото, видео...) в файловой системе на сервере, а в БД - лишь ссылка на соответствующий ресурс.
> Не нужно пытаться запихнуть в БД то, что туда не влазит.
> К тому же, web-сервер и ОС могут кешировать эти данные... чего не скажешь о запросах к БД.

Тут нужно с акцентировать ,что `photo` в `IUserRegistrationData` это файловый объект, не url. Для его получения в форме регистрации будет использоваться html element:
```html
<input type="file" >
```
Файловый объект, нужно будет загрузить на наш сервер (непосрдественно в БД, или рядом положить - это детали реализации), но отправить нужно бинарный файл

А вот IUser это объект, с которым мы работаем, после того как пользователь залогинился и он нам нужен чтобы:
 1. Отображать иконку пользователя в Header (в требованиях нет, но я не понимаю, как по другому продемонстрировать, что мы работаем с фото пользователя)
 2. Проверять, проголосовал ли уже пользователь за достопримечательность
 3. Сохранять сессию при перезагрузке страницы

Теперь по пунктам:
 1. Можно и не отображать, в требованиях это нет. Просто в поле регистрации, после того, как пользователь выбрал изображение, тут же его в форме показывать в элементе img, и отправлять на сервер. Всё, требование выполнено. Если же мы его отображаем в Header  - то мы должны получить либо бинарные данные с бекенда в ответе на авторизацию или `photoUrl`, но тогда наш бекенд долежн выполнять роль файлообменника и генерировать url для файлов которые "лежат рядом с БД"
 2. Можно и не проверять, как я писал выше: проверить можно на стороне бекенда, если пользователь проголосвовал ранее, просто менять старую оценку на новую. Иначе нужен `id`
 3. Здесь, согласен, мы не работаем на прямую с `token`, и нам не нужно к нему получать доступ. Можно удалить и это поле из IUser

Вобще склоняюсь к тому, чтобы использовать готовые решения. например тотже [Auth0](https://auth0.com/docs/users/user-profile-structure#user-profile-attributes) полностью покрывает наши потребности

2021-03-06 18:23 UTC, natallia-js commented on src/entities/userRegisterData.ts
> +interface IUserRegisterData extends IUser {
Итак, надо что-то решать. И двигаться дальше. Не тот проект, над которым стоит вести долгие дискуссии.
IUser оставляем. В нем будет photoUrl и token (его генерирует для клиента сервер в ответ на авторизацию, передает клиентской части, клиент отдает token серверу в запросе на проставление рейтинга, сервер верифицирует данный token и, если он в порядке, извлекает из него id и выполняет запрос пользователя)

2021-03-07 07:11 UTC, AnnaDavydenko reviewed
я бы сделала у всех id тип number

2021-03-07 20:03 UTC, aplatkouski commented on src/entities/userRegisterData.ts
> +interface IUserRegisterData extends IUser {
``путь в ФС пользователя`` - возможно я что-то не понимаю, но что мы дальше будем делать со сторокой, которая содерижт путь к фалу изображения на компьютере пользователя?

2021-03-07 20:04 UTC, aplatkouski commented
> я бы сделала у всех id тип number

Это зависит от реализации БД. У нас MongoDB и там своя реализация, предположу построена на `uuid`

2021-03-07 21:54 UTC, natallia-js commented on src/entities/userRegisterData.ts
> +interface IUserRegisterData extends IUser {
В момент регистрации пользователь выбирает с помощью диалогового окна файл со своей фотографией. Данный файл фронтенд может подгрузить и отобразить картинку на экране, еще до нажатия кнопки "зарегистрироваться" (как-то же надо img сказать, откуда брать файл)
Но если после выбора файла и закрытия диалогового окна выводить не картинку не нужно, а по умолчанию выводить название файла, который пользователь выбрал, тогда, конечно photoPath не нужен.

2021-03-07 22:25 UTC, aplatkouski approved these changes
Спасибо за отлично сделанную работу!
🎉

2021-03-08 10:05 UTC, Helias17 approved these changes

2021-03-08 13:48 UTC, AnnaDavydenko approved these changes

2021-03-09 20:38 UTC, merged