feat: add header, basic styles
aplatkouski/travel-app pull request #3
Opened 2021-03-07 19:16 UTC by AnnaDavydenko

2021-03-07 21:36 UTC, Helias17 approved these changes

2021-03-08 01:44 UTC, aplatkouski commented
1. Необходимо добавить ссылку на главную страницу, при клике на лого
2. Если тебя не затруднит, добавь так же кнопку `Log out`, я потом прикручу redux-state, чтобы в зависимости от статуса пользователя, отображалась та или иная кнопка
3.

2021-03-08 01:46 UTC, aplatkouski requested changes
Я частично переписал твой код

См. последний комментарий

2021-03-08 12:54 UTC, AnnaDavydenko commented
> 1. Необходимо добавить ссылку на главную страницу, при клике на лого
> 2. Если тебя не затруднит, добавь так же кнопку `Log out`, я потом прикручу redux-state, чтобы в зависимости от статуса пользователя, отображалась та или иная кнопка

+

2021-03-09 22:33 UTC, aplatkouski approved these changes

2021-03-09 22:45 UTC, merged